mode: phase1

star:
  genome_index: /net/trapnell/vol1/home/coletrap/teaching/genome569/reference
  whitelist: /net/trapnell/vol1/home/coletrap/teaching/genome569/barcode-whitelists/737K-august-2016.txt
  cb_length: 16
  umi_start: 17
  umi_length: 10
  threads: 8

paths:
  full_counts_dir: provided/full_counts
  full_counts_matrix_dir: provided/full_counts/filtered
  reference_table_s4: reference/packer_table_s4.tsv

results_dir: results
notebook: notebooks/analysis.Rmd
sample_sheet: provided/mini_samples.tsv
# To explore what a full run would look like, you could switch this to
# provided/samples.tsv, but you are not expected to process the full dataset.

umap_dims: 30
cluster_resolution: 1e-3
